version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # This is the proper way to set Node version in CodeBuild
    commands:
      - node --version
      - npm --version
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      # Fix npm optional dependencies bug
      - rm -rf node_modules package-lock.json || true
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist